from enum import Enum


class HttpStatusCode(int, Enum):
    OK = 200
    CREATED = 201
    FOUND = 302
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    REQUEST_TIMEOUT = 408
    INTERNAL_SERVER_ERROR = 500
    SERVICE_UNAVAILABLE = 503


class StatusCode(str, Enum):
    SUCCESS = "SUCCESS"
    WARNING_CONTINUE_REDIRECT = "WARNING_CONTINUE_REDIRECT"
    WARNING_CONTINUE_3DS = "WARNING_CONTINUE_3DS"
    WARNING_CONTINUE_CVV = "WARNING_CONTINUE_CVV"
    ERROR_SYNTAX = "ERROR_SYNTAX"
    ERROR_VALUE_INVALID = "ERROR_VALUE_INVALID"
    UNAUTHORIZED = "UNAUTHORIZED"
    DATA_NOT_FOUND = "DATA_NOT_FOUND"


class OrderStatus(str, Enum):
    NEW = "NEW"
    COMPLETED = "COMPLETED"
    WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"


class RequestMethod(str, Enum):
    POST = "POST"
    PUT = "PUT"
    GET = "GET"
